# Generated by Django 6.1.1 on 2026-10-02 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_auth', '0002_delete_teachermodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('basicinfomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_auth.basicinfomodel')),
                ('teacher_id', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/teacher_img')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('users_auth.basicinfomodel',),
        ),
    ]
