# Generated by Django 6.1.1 on 2026-10-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
